### ISSUE TITLE
Unable to Auth

### ISSUE THREAD

**Issue by OIK2** [jaymoulin/docker-google-musicmanager#3]
When authorizing, it now gives me a new error message:

root@raspberrypi:~# docker exec -ti googlemusicmanager auth
__init__() takes at most 4 positional arguments (5 given)

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?client_id=xxxxxxxxxx.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusi
cmanager&access_type=offline&response_type=code
Follow the prompts, then paste the auth code here and hit enter: xxxxxxxxxxxxxxxxxxxxxxxxxx  
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 995, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/auth.py", line 11, in <module>
    if api.perform_oauth(path) == True:
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 101, in perform_oauth
    credentials = flow.step2_exchange(code)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1002, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com
```

**Comment by jaymoulin** [comment]
looks like you don't have access to internet through your docker container.
```
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com
```
Do you have a proxy or something?

**Comment by OIK2** [comment]
no, I have it connected directly to my router.  I am running Docker within an installation of Openmediavault (Debian).  I was able to do the pull with no problem, so outside of the container has internet access.
I am not sure if this could help show any problems, it is the OMV Docker-GUI Details output for the container:
https://pastebin.com/kYtcc310

**Comment by jaymoulin** [comment]
Does `sudo ping www.googleapis.com` work on your host?
If yes, does `docker exec -ti googlemusicmanager ping www.googleapis.com` gives you a similar result?
If no, maybe you should check your docker daemon to connect through your router or considering use of bridged network driver for Docker.

a possible quickfix would be to add `--net=host` param to your container creation command but it's a bit extreme...

I was not able to reproduce this issue with the latest image (0.2.2) so I guess it's specific to your configuration.

**Comment by OIK2** [comment]
Ended up going the `--net=host` route, but that fixed the problem!  Thank you  :-)
